source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target ‘LoginAndView’ do
    pod 'AWSCore', '~> 2.5.0'
    pod 'AWSCognitoIdentityProvider', '~> 2.5.0'
    pod 'AWSDynamoDB', '~> 2.5.0'
    pod 'AWSS3', '~> 2.5.0'
end
